// script.js - HSK Exercise Site
const HSK_DATA={1:{name:'HSK 1',subtitle:'Sơ Cấp',lessons:Array.from({length:15},(_,i)=>({id:'hsk1-bai'+(i+1),title:'Bài '+(i+1),content:'<h2>HSK 1 - Bài '+(i+1)+'</h2><p>Phần đề bài sẽ được bổ sung tại đây.</p>'}))},2:{name:'HSK 2',subtitle:'Sơ-Trung Cấp',lessons:Array.from({length:15},(_,i)=>({id:'hsk2-bai'+(i+1),title:'Bài '+(i+1),content:'<h2>HSK 2 - Bài '+(i+1)+'</h2><p>Phần đề bài sẽ được bổ sung tại đây.</p>'}))},3:{name:'HSK 3',subtitle:'Trung Cấp',lessons:Array.from({length:15},(_,i)=>({id:'hsk3-bai'+(i+1),title:'Bài '+(i+1),content:'<h2>HSK 3 - Bài '+(i+1)+'</h2><p>Phần đề bài sẽ được bổ sung tại đây.</p>'}))},4:{name:'HSK 4',subtitle:'Trung-Cao Cấp',lessons:Array.from({length:15},(_,i)=>({id:'hsk4-bai'+(i+1),title:'Bài '+(i+1),content:'<h2>HSK 4 - Bài '+(i+1)+'</h2><p>Phần đề bài sẽ được bổ sung tại đây.</p>'}))}};
let currentLevel=null;
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));const t=document.getElementById(id);if(t){t.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});}}
function openLevel(n){currentLevel=n;const d=HSK_DATA[n];if(!d)return;document.getElementById('list-title').textContent=d.name+' - '+d.subtitle;const g=document.getElementById('lesson-grid');g.innerHTML='';d.lessons.forEach((l,i)=>{const c=document.createElement('div');c.className='lesson-card';c.setAttribute('role','button');c.setAttribute('tabindex','0');c.innerHTML='<span class="lesson-number">'+(i+1)+'</span><span class="lesson-label">'+l.title+'</span>';c.addEventListener('click',()=>openLesson(i));c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')openLesson(i);});g.appendChild(c);});showScreen('screen-list');}
function openLesson(i){const d=HSK_DATA[currentLevel];if(!d)return;const l=d.lessons[i];if(!l)return;document.getElementById('lesson-title').textContent=d.name+' - '+l.title;const b=document.getElementById('lesson-body');if(l.content.includes('bổ sung tại đây')){b.innerHTML='<div class="placeholder-block"><div class="placeholder-hanzi">学</div><h2 style="color:var(--red-deep);font-family:serif;">'+d.name+' - '+l.title+'</h2><p class="placeholder-text">Nội dung chưa được bổ sung. Mở script.js và tìm id: <strong>'+l.id+'</strong> để chỉnh sửa.</p></div>';}else{b.innerHTML=l.content;}showScreen('screen-lesson');}
document.getElementById('btn-back-home').addEventListener('click',()=>showScreen('screen-home'));
document.getElementById('btn-back-list').addEventListener('click',()=>showScreen('screen-list'));
document.querySelectorAll('.level-card').forEach(card=>{const lv=parseInt(card.getAttribute('data-level'),10);card.addEventListener('click',()=>openLevel(lv));card.setAttribute('role','button');card.setAttribute('tabindex','0');card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')openLevel(lv);});});
showScreen('screen-home');
